name: Java 
  
on: push
jobs:
  build-java:
    runs-on: ubuntu-latest
    container: maven:latest
    steps:
      - name: Check Java version
        run: java -version

      - name: Check Maven version
        run: mvn --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile Java App
        run: javac HelloWorld.java

      - name: Run Java App
        run: java HelloWorld.java
